### ISSUE TITLE
Y7000 HDMI 无法使用

### ISSUE THREAD

**Issue by lx200916** [hnie-xwz/EFI#11]
Y7000 HDMI 无法使用，外接显示器无反应

**Comment by lx200916** [comment]
版本是10.14

**Comment by XiewzHub** [comment]
很抱歉，这个功能我暂时无法解决，因为没有显示器，无法调试，如果你能找到大神解决掉请提供给我。感激不尽~~~ @lx200916

**Comment by lx200916** [comment]
感谢回复😜我也在找解决方案😄期待能解决

Xiewz666 <notifications@github.com> 于 2018年12月12日周三 上午11:41写道：

**Comment by xiaoMGitHub** [comment]
貌似Y7000 HDMI输出是走独显的，可以试试type-c转HDMI看看能不能输出
