### ISSUE TITLE
Type C视频转接器无法使用 

### ISSUE THREAD

**Issue by lx200916** [hnie-xwz/EFI#18]
连接Type C转HDMI转接器时无法使用，可以识别出名称但是无法使用。看速度是识别为USB1.0设备了
![66941dad5e620be3bb1311479618abf1](https://user-images.githubusercontent.com/44310445/51014241-8a8e2480-15a1-11e9-81a2-9d1be48dd452.png)

**Comment by donblack01** [comment]
同无法使用

**Comment by ramblerSY** [comment]
和usb转接线有关还是不能使用，有没有大神成功的呢，用的什么牌子的转接线
