### ISSUE TITLE
y7000p 插入耳机后声音只有背景声而没有人声部分，测试了QQ音乐和哔哩哔哩

### ISSUE THREAD

**Issue by D10NGYANG** [hnie-xwz/EFI#22]
正常扬声器播放OK，插入耳机也能自动切换到耳机输出。不过看视频听音乐时，只有背景音乐而没有人声，耳机是苹果原装耳机

**Comment by XiewzHub** [comment]
方法一：下载这个，解压后，双击运行安装，重建缓存重启。[alc_fix.zip](https://github.com/XiewzHub/EFI/files/2986160/alc_fix.zip)

方法二：插上耳机，打开声音设置，找到输入，拖动声道调节条往左或往右。

**Comment by D10NGYANG** [comment]
> 方法一：下载这个，解压后，双击运行安装，重建缓存重启。[alc_fix.zip](https://github.com/XiewzHub/EFI/files/2986160/alc_fix.zip)
> 
> 方法二：插上耳机，打开声音设置，找到输入，拖动声道调节条往左或往右。

还是不行。。。。。。。。

**Comment by XiewzHub** [comment]
具体哪个方法不行？有什么体现 @D10NGYANG

**Comment by D10NGYANG** [comment]
首先尝试了方法一：双击“install双击自动安装.command”运行后，提示“成功，重建缓存，重新启动”，我就执行重新启动。启动后，打开QQ音乐，插入耳机，仍旧只能听到背景音乐，而缺少人声部分。好比如只有伴奏（已确保这首歌不是伴奏版）。然后打开【系统偏好设置】找到【声音】执行方法二，在输出页能看到【耳机】调整输出音量往大里调能听到一点人声，但是比较微弱，远小于背景音乐。

**Comment by XiewzHub** [comment]
你试试，先卸载方法一的，压缩包里有卸载的执行文件；然后方法二那个声道调节要调成左声道或者右声道。不要把滑块放在中间位置。两个方法只要用其中一种，如果尝试后都不行，那我就得给我仔细瞧瞧了。

**Comment by D10NGYANG** [comment]
可以了哈哈哈哈哈，卸载了方法一的，方法二调成左声道或右声道都可以。非常感谢🙏
