### ISSUE TITLE
BCM94352z Wi-Fi成功使用，但是蓝牙搜索不到设备

### ISSUE THREAD

**Issue by D10NGYANG** [hnie-xwz/EFI#23]
之前没有装这个BCM94352z，今天到的，就安装上了。启动后在Windows下使用正常，在mac下只能Wi-Fi正常使用，蓝牙搜索不到设备

**Comment by XiewzHub** [comment]
@D10NGYANG 把对应的蓝牙驱动放到LE目录下，然后重建缓存，重启即可

**Comment by D10NGYANG** [comment]
我这样做后，重启。蓝牙变成不可用了。。。另外我的有线鼠标和无限鼠标都用不了了。。。现在应该怎么操作？

**Comment by D10NGYANG** [comment]
对应的蓝牙驱动指哪些？难道我放错了？

**Comment by D10NGYANG** [comment]
我再次重启后，鼠标可以控制了，但是蓝牙依旧不可用

**Comment by D10NGYANG** [comment]
我存放的路径为：‎⁨Mac⁩ ▸ ⁨资源库⁩ ▸ ⁨Extensions⁩；放入的文件是：AirportBrcmFixup_Release_v1.1.9.kext、BrcmFirmwareRepo_Release_v.2.2.10.kext、BrcmPatchRAM2_Release_v.2.2.10.kext.kext；是不是我放进了系统路径里，我还需要把在EFI的相同文件删除？

**Comment by XiewzHub** [comment]
@D10NGYANG 没错，就是这三驱动，原来的efi里面的不需要删除。如果驱动不了有可能是没插好或者插反了。先去win下看看蓝牙还正常不正常。能够连上设备

**Comment by D10NGYANG** [comment]
win下找不到蓝牙了。。。蒙逼。。。WiFi还行，又要拆机

**Comment by D10NGYANG** [comment]
重新插拔也没有了。。。。不会挂了吧。。。。哭

**Comment by XiewzHub** [comment]
@D10NGYANG 不会的，WiFi能工作，应该没坏，你把引脚线对调插，然后启动的时候先进win，重启几次，把蓝牙加载出来再去mac

**Comment by D10NGYANG** [comment]
https://jingyan.baidu.com/article/455a99504dc88fa16727784c.html用了这个办法，蓝牙又出现了。重新来一次

**Comment by D10NGYANG** [comment]
不过进mac要好久好久。进去之后又是看不到蓝牙，鼠标键盘不能动。回到win又有蓝牙。。。。蒙圈

**Comment by D10NGYANG** [comment]
第三次重启，终于成功了！感谢！airdrop也能正常使用了。看下稳定不

**Comment by XiewzHub** [comment]
@D10NGYANG 重新插一次网卡，不要让线的金属接触其他金属

**Comment by XiewzHub** [comment]
@D10NGYANG 成功了就好，先试试各种操作，确定稳定下来就合盖子

**Comment by D10NGYANG** [comment]
嗯嗯，好的！

**Comment by D10NGYANG** [comment]
找到问题了。是我的无线鼠标。只要去链接我的罗技M590，就会出问题。好像网上的说法是蓝牙WI-FI同频。。如果去链接M590的话，接下来蓝牙就会不起作用。需要重建缓存，重启才会恢复。然后链接AirPods和手机蓝牙都测试可以
