### ISSUE TITLE
电池电量不会更新的问题

### ISSUE THREAD

**Issue by D10NGYANG** [hnie-xwz/EFI#24]
我又来了。新问题。电池在第一次开机时会读取一次正常的状态。接下来电量变少并不会更新。就算插上电源充电也不会有提示，也不会随着电量增加而更新电量

**Comment by XiewzHub** [comment]
@D10NGYANG 难道是缺了什么没传上？？明天我把自己正在用的打包一份给你试试。

**Comment by D10NGYANG** [comment]
好的！麻烦了！感谢！

**Comment by XiewzHub** [comment]
[CLOVER.zip](https://github.com/XiewzHub/EFI/files/2994993/CLOVER.zip)
现用这个试试，这是我自己EFI里复制出来的，过两天我再检查一下是否漏了东西没有上传

**Comment by D10NGYANG** [comment]
啊，还是不行。一样的结果。在系统报告里能看到电源电池信息，状态栏也会有电池图标和电量百分比。但是不会更新状态。开机时什么状态就是一直固定这个状态。好比如开机时没插电源，电量剩余50%，插上电后，状态栏图标并不会更新为充电中的标志，充电一段时间后也不会更新电池百分比，仍旧是50%。。。。好消息是，点击电池图标，切换显示百分比，就能读取当前的电池状态更新状态栏的图标一次。然后依旧不会自动更新

**Comment by XiewzHub** [comment]
额。。清缓存也一样？如果这样的话，那就只能用最新的电池驱动，替换试试。理论上应该没问题呀。我用这么久了。。。

**Comment by D10NGYANG** [comment]
对的，重建缓存也是一样。可能我这台机器有啥不一样？我只能在系统报告里看到我的电池序列号为：SMP-9490。最新的电池驱动哪里下载呢？

**Comment by XiewzHub** [comment]
https://bitbucket.org/RehabMan/os-x-acpi-battery-driver/downloads/   @D10NGYANG

**Comment by D10NGYANG** [comment]
好的，十分感谢！我现在就去试试！

**Comment by D10NGYANG** [comment]
用了最新版本完美实现！能够实时更新电池电量了！不过。。这电量掉的是真的快。。。。看着让人续航焦虑症。十分感谢！目前应该除了HDMI和触摸板应该都很完善了

**Comment by XiewzHub** [comment]
@D10NGYANG 好的，你试试仪盘表的添加效果能不能正常显示，我之前没有用最新的是因为那个效果会花屏，用老驱动就不会花屏。在`系统报告`的`显示器`属性里可以看到`屏幕色彩参数`，如果是`30`代表是有问题的，可能会花屏，如果是`24**8888`的这样子的话就正常。虽然那个一般不影响使用

**Comment by D10NGYANG** [comment]
有一个`帧缓冲深度：	30 位彩色 (ARGB2101010)`。不过仪表盘里的操作没有问题，虽然从来没用过仪表盘，就算有影响也没有关系哈哈哈。暂时没遇到其他地方花屏的问题
