### ISSUE TITLE
请问10.14下启动出现panic错误,如何解决?

### ISSUE THREAD

**Issue by alexlipe** [hnie-xwz/EFI#3]
二次启动时报panic错误, 位置时在AppleInetlCFLGraphicsFramebuffer. 
你如何解决的?
我已经尝试了补丁..都无效...

**Comment by hnie-xwz** [comment]
@alexlipe 你装10.13.6  17g2112那个版本，10.14的还没有完全做好，如果你硬要装的话只能去掉intel显卡 注入，那样会导致显卡无法驱动，比较卡，所以还是10.13.6吧，以后我有空再继续完善efi

**Comment by alexlipe** [comment]
好嘞,非常感谢.
