### ISSUE TITLE
黑屏频繁，且使用一段时间后出现掉帧情况

### ISSUE THREAD

**Issue by lx200916** [hnie-xwz/EFI#6]
成功亮屏三次左右后便无法亮屏

**Comment by lx200916** [comment]
发现了规律。。睡眠有问题😂睡眠后就无法亮屏，除非强行重启一次

**Comment by XiewzHub** [comment]
先取消独立显卡
![](http://ww1.sinaimg.cn/large/e8450fe4gy1fwieplneulj21100m0te9.jpg)
然后把随眠关掉，电池和电源适配器都要拖到最后“永不”的地方
![](http://ww1.sinaimg.cn/large/e8450fe4gy1fwiesa7o45j20lo0fjtb5.jpg)

**Comment by XiewzHub** [comment]
@lx200916 另外，这个启动几次才亮屏的问题我也很困扰，一直得不到解决方法，愁死我了。。。
无法睡眠，无法用触摸板都无所谓，但不能一次性完美开机，靠运气开机就不能忍了。  😂

**Comment by lx200916** [comment]
已经关闭了睡眠了😂有时隔一段时间不开机（比如一晚上）再开机也会黑屏，现在只能在黑屏状态下等待完全启动后强行关机，基本可以保证第二次完美亮屏，

**Comment by XiewzHub** [comment]
@lx200916 用macos10.14分支的efi可以装
macos10.14系统，启动不黑屏了

**Comment by lx200916** [comment]
更新10.14，问题解决 XD
